# Generated by Django 3.2.8 on 2021-10-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Nmae',
            new_name='Name',
        ),
    ]
